# Generated by Django 4.2.2 on 2023-06-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tarefa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
